One last task to merge back to main: Cannot deserialize field in base class with entt, i.e. AnsonBody.a = "test".
github\anson.cmake\tests\t03_deserialize.cpp(144): error: Expected equality of these values:
  "test/echo"
  reqbd.a
    Which is: ""
[4] a = test/echo

[  FAILED  ] Anson.AnsonMsg_EchoReq (9 ms)
[----------] 1 test from Anson (9 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (9 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Anson.AnsonMsg_EchoReq