14 of 15 tests runs
[==========] 15 tests from 5 test suites ran. (231 ms total)
[  PASSED  ] 14 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Anson.AnsonMsg_EchoReq

 1 FAILED TEST
github\anson.cmake\tests\t03_deserialize.cpp(120): error: Expected equality of these values:
  Port::echo
    Which is: "echo.less"
  msg->port
    Which is: "echo.less"
[1] msg->port