11 of 12 tests runs
[----------] Global test environment tear-down
[==========] 12 tests from 5 test suites ran. (242 ms total)
[  PASSED  ] 11 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Anson.AnsonMsg_EchoReq

 1 FAILED TEST
github\anson.cmake\tests\t03_deserialize.cpp(223): error: Expected equality of these values:
  "test/echo"
  reqbd.a
    Which is: ""
[4] a = test/echo